// src/health/tips.ts
export const healthTips: string[] = [
  "💧 Drink at least 8 glasses of water daily to stay hydrated and flush out toxins.",
  "🍎 Include more fruits and vegetables in your meals for essential vitamins and fiber.",
  "🏃‍♂️ Exercise for at least 30 minutes every day to maintain heart health.",
  "😴 Aim for 7–8 hours of quality sleep each night to support body recovery.",
  "🧘‍♀️ Practice deep breathing or meditation to reduce stress and improve focus.",
  "🍵 Limit caffeine intake to prevent dehydration and improve sleep quality.",
  "🥗 Avoid skipping breakfast — it helps regulate metabolism and energy levels.",
  "🚶‍♀️ Take short walks after meals to aid digestion and maintain blood sugar levels.",
  "🚫 Avoid smoking — it increases the risk of heart disease and respiratory problems.",
  "🧴 Use sunscreen daily to protect your skin from harmful UV rays.",
  "💪 Strength training twice a week helps maintain muscle mass and bone density.",
  "🥦 Eat foods rich in omega-3 fatty acids for brain and heart health.",
  "🍌 Snack on nuts or fruits instead of processed chips or candy.",
  "🥤 Reduce sugary drink consumption to maintain a healthy weight.",
  "👟 Choose stairs over elevators to add natural exercise to your day.",
  "🥬 Include fiber-rich foods like oats and beans to support gut health.",
  "🧂 Limit salt intake to reduce blood pressure risks.",
  "📱 Take screen breaks every 30–40 minutes to relax your eyes.",
  "🍋 Start your day with a glass of lemon water to boost digestion.",
  "🧠 Challenge your brain daily — read, learn, or solve puzzles.",
  "🚰 Carry a reusable water bottle to stay hydrated on the go.",
  "🥥 Use healthy oils like olive or coconut oil for cooking.",
  "💤 Maintain a consistent sleep schedule — go to bed and wake up at the same time.",
  "🥛 Choose low-fat dairy or plant-based milk for heart health.",
  "🍇 Eat colorful foods — different colors mean different nutrients!",
  "🚴‍♂️ Try cycling or swimming to make workouts more enjoyable.",
  "🧄 Add garlic to meals for natural immunity support.",
  "🥕 Eat raw veggies as snacks for better fiber intake.",
  "🌞 Get 15 minutes of sunlight daily for vitamin D.",
  "🥜 Include nuts and seeds to boost good fats in your diet.",
  "🍫 Choose dark chocolate over milk chocolate for antioxidants.",
  "🫖 Replace soda with green tea for better metabolism.",
  "🍊 Eat citrus fruits for a natural vitamin C boost.",
  "🪥 Brush and floss your teeth twice daily for oral hygiene.",
  "👂 Listen to your body — rest when you feel exhausted.",
  "🧃 Avoid fruit juices with added sugars — go for fresh fruit instead.",
  "🚿 End your shower with cool water to improve circulation.",
  "📖 Read before bed instead of using your phone to sleep better.",
  "🧴 Moisturize your skin regularly to prevent dryness.",
  "🍽️ Practice portion control — stop eating when 80% full.",
  "👀 Schedule regular eye checkups if you spend long hours on screens.",
  "🥔 Choose baked or grilled foods instead of fried options.",
  "🍞 Opt for whole-grain bread over refined white bread.",
  "🫐 Add berries to your breakfast for antioxidants.",
  "🎧 Listen to calm music to relax your mind after a long day.",
  "💬 Stay socially connected — healthy relationships boost mental well-being.",
  "🪑 Keep good posture when sitting to protect your back.",
  "🫶 Express gratitude daily — it improves happiness levels.",
  "💨 Practice slow, mindful breathing when stressed.",
  "🌿 Keep indoor plants — they purify air and lift mood.",
  "💡 Take breaks during work to stretch and reset focus.",
  "🚶‍♂️ Aim for 8,000–10,000 steps daily for active living.",
  "🩺 Schedule regular health checkups for early detection.",
  "🍳 Include protein in every meal to support muscles.",
  "🍓 Choose seasonal produce for maximum freshness.",
  "🥶 Avoid eating too late at night to improve digestion.",
  "🧊 Use cold compresses for quick relief from inflammation.",
  "🧺 Keep your surroundings clean to prevent infections.",
  "🐟 Eat fish twice a week for omega-3 benefits.",
  "🥒 Stay cool with water-rich foods like cucumber and watermelon.",
  "🧑‍🍳 Cook at home more often — it’s healthier and cheaper.",
  "🫁 Take deep breaths in fresh air to improve lung health.",
  "🥄 Avoid added sugar in tea or coffee whenever possible.",
  "📅 Plan your meals weekly to make healthier food choices.",
  "🍂 Take time to relax outdoors — nature reduces anxiety.",
  "🧴 Wash your hands often — small habit, big protection.",
  "🪞 Smile often — it reduces stress and uplifts others.",
  "🍚 Eat smaller, frequent meals instead of heavy ones.",
  "🍉 Eat fruit instead of dessert to satisfy sweet cravings.",
  "💻 Adjust your monitor to eye level to prevent neck strain.",
  "🚿 Take a shower after exercise to refresh your body.",
  "🛌 Keep your bedroom dark and quiet for better sleep.",
  "🧘 Stretch your body every morning to improve flexibility.",
  "🦷 Visit your dentist twice a year for routine cleaning.",
  "💧 Start your morning with a glass of warm water.",
  "🎯 Set realistic health goals — consistency matters more than perfection.",
  "🥬 Add spinach or kale to smoothies for extra nutrients.",
  "👣 Walk barefoot on grass occasionally — it’s grounding.",
  "📵 Disconnect from social media for a few hours daily.",
  "🧺 Change bedsheets regularly for better hygiene.",
  "🧄 Add ginger and turmeric to your diet for anti-inflammatory benefits.",
  "🥕 Include carrots to support healthy vision.",
  "🍗 Choose lean protein sources like chicken or tofu.",
  "🍠 Eat sweet potatoes instead of regular fries.",
  "🍶 Stay mindful about alcohol intake — moderation is key.",
  "🧴 Protect lips with SPF balm when outdoors.",
  "🫶 Compliment yourself — self-kindness improves motivation.",
  "🍽️ Avoid multitasking while eating — focus on your food.",
  "🚴 Add music or podcasts to make workouts fun.",
  "🧤 Keep your hands moisturized to prevent cracking.",
  "💬 Talk about your feelings — it lightens mental load.",
  "📚 Learn something new each month to keep your brain active.",
  "🍲 Prepare balanced meals — protein, carbs, fats, and fiber.",
  "🥭 Eat local and fresh fruits — better taste and nutrients.",
  "🪟 Open windows daily to improve ventilation indoors.",
  "💡 Spend time in natural light for better mood regulation.",
  "🧃 Blend fresh fruit smoothies instead of processed drinks.",
  "🦵 Do leg stretches every few hours to improve circulation.",
  "🧂 Read nutrition labels — avoid hidden sodium and sugars.",
  "🍗 Grill or steam food rather than frying it.",
  "🧀 Limit cheese intake if you’re lactose-sensitive.",
  "🧹 Declutter your workspace — clean space, clear mind.",
  "🥶 Store leftovers properly to avoid foodborne illnesses.",
  "🧍‍♀️ Take standing breaks if you work at a desk.",
  "🚰 Add cucumber or mint to water for a refreshing twist.",
  "🧊 Ice sore muscles after intense workouts.",
  "🕯️ Light a candle or incense to relax your senses.",
  "📈 Track your habits to stay accountable to goals.",
  "🧴 Apply moisturizer right after showering to lock in moisture.",
  "📞 Call family or friends regularly to strengthen emotional bonds.",
  "🥦 Steam vegetables to preserve nutrients.",
  "🌙 Avoid blue light before bed for deeper sleep.",
  "🪩 Dance for 10 minutes a day — it’s fun and burns calories.",
  "🍳 Use non-stick pans to reduce oil usage.",
  "💊 Don’t self-medicate — always consult a doctor.",
  "🧤 Keep nails clean and trimmed to prevent infection.",
  "🪥 Replace your toothbrush every 3 months.",
  "💧 Drink more water before meals — helps portion control.",
  "🦻 Listen to relaxing sounds before sleeping.",
  "📆 Schedule ‘no-screen’ hours for mental recharge.",
  "🧘 Stretch gently after workouts to prevent soreness.",
  "🫛 Add lentils and beans for plant-based protein.",
  "🌾 Eat whole grains instead of refined grains.",
  "🥩 Limit red meat consumption to once a week.",
  "🧃 Drink smoothies with spinach, banana, and yogurt for energy.",
  "🧴 Wash your face before bed to prevent acne.",
  "📱 Avoid checking phone immediately after waking up.",
  "🧘‍♂️ Do mindfulness meditation for 5 minutes daily.",
  "🎧 Listen to your favorite music to lift your mood.",
  "🍅 Eat tomatoes regularly for better skin health.",
  "🫐 Blueberries support brain function and memory.",
  "💧 Refill your water bottle after every meal.",
  "🥝 Eat kiwi for vitamin C and digestion aid.",
  "🧀 Try probiotic foods like yogurt for gut health.",
  "🚴 Stretch before and after workouts to prevent injury.",
  "📖 Write a short gratitude note daily.",
  "🧂 Use herbs instead of salt to flavor food.",
  "🧠 Keep learning — cognitive activity prevents decline.",
  "🍄 Mushrooms boost immunity and vitamin D.",
  "🛌 Nap for 20 minutes if you feel fatigued.",
  "🚫 Limit processed foods for better energy levels.",
  "🍳 Eat eggs — great source of protein and choline.",
  "🫀 Check blood pressure annually.",
  "🥤 Avoid drinking through straws — can cause bloating.",
  "🧴 Clean your phone screen daily — it carries bacteria.",
  "🧼 Wash fruits and veggies thoroughly before eating.",
  "📺 Stretch during TV commercials instead of sitting idle.",
  "🪑 Use ergonomic chairs for better posture.",
  "🚰 Add lemon to water for vitamin C and detox.",
  "🥯 Avoid white flour — choose whole grain alternatives.",
  "🍇 Eat grapes for antioxidants and hydration.",
  "🧘‍♀️ Try yoga poses for relaxation and flexibility.",
  "🧄 Garlic strengthens the immune system naturally.",
  "📦 Meal-prep on weekends to save time and eat healthy.",
  "🥦 Broccoli supports bone and immune health.",
  "💬 Celebrate small fitness achievements — consistency wins.",
  "🧴 Keep a hand sanitizer handy while traveling.",
  "🧘 Try morning stretches to wake up your body gently.",
  "🍵 Herbal teas support relaxation and digestion.",
  "🥗 Add avocado for healthy fats.",
  "🧺 Wash workout clothes frequently to avoid odor.",
  "🍋 Lemon water supports hydration and skin glow.",
  "🍠 Sweet potatoes are high in fiber and vitamin A.",
  "🚿 Cold showers improve alertness and circulation.",
  "🧘 End your day with gratitude journaling.",
  "🪴 Keep aloe vera — great for skin and air purification.",
  "🍫 Dark chocolate improves mood and blood flow.",
  "🧊 Apply ice under eyes to reduce puffiness.",
  "🍅 Cook tomatoes — cooked ones release lycopene better.",
  "🥗 Add herbs like basil, thyme, or parsley for extra flavor.",
  "🧃 Drink vegetable juice occasionally for detox benefits.",
  "🚶 Walk after heavy meals to avoid sluggishness.",
  "🌾 Oats support cholesterol balance and digestion.",
  "💬 Share health goals with a friend for accountability.",
  "🪞 Affirm positivity in front of a mirror every morning.",
  "🌻 Get morning sunlight to regulate circadian rhythm.",
  "🥑 Avocados promote brain and skin health.",
  "🧘 Try deep breathing for instant stress relief.",
  "🧴 Keep skin hydrated, especially during winter.",
  "🚰 Drink more water in hot weather to prevent dehydration.",
  "🧂 Avoid overly salty snacks — they retain water.",
  "🍓 Berries reduce inflammation and support heart health.",
  "🧠 Laugh often — it releases feel-good hormones.",
  "🍚 Brown rice is a healthy alternative to white rice.",
  "🥬 Green leafy veggies detoxify and energize the body.",
  "🧘‍♂️ End your day with gratitude — peaceful sleep guaranteed.",
];
